### ISSUE TITLE
DLL build error VS2022 compile with /bigobj

### ISSUE THREAD

**Issue by elvrik** [swordbluesword/PalWorld-NetCrack#14]
`PalWorld-NetCrack-master\SDK\Pal_functions.cpp : fatal  error C1128: number of sections exceeded object file format limit: compile with /bigobj
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by xCENTx** [comment]
> Right click solution -> Properties
> C/C++: All Options -> Additional Options: "/bigobj" 
![image](https://github.com/swordbluesword/PalWorld-NetCrack/assets/80198020/6d4603f3-4782-4b01-ae6f-dca5f6c11d7e)

**Comment by elvrik** [comment]
> > Right click solution -> Properties
> > C/C++: All Options -> Additional Options: "/bigobj"
> > Alternatively you can compile in "Release Mode"
> > ![image](https://private-user-images.githubusercontent.com/80198020/299693789-6d4603f3-4782-4b01-ae6f-dca5f6c11d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTk3NTgsIm5iZiI6MTcwNjE5OTQ1OCwicGF0aCI6Ii84MDE5ODAyMC8yOTk2OTM3ODktNmQ0NjAzZjMtNDc4Mi00YjAxLWFlNmYtZGNhNWY2YzExZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE2MTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYTU3M2Y5YWUwY2VmODRkYTBkZjBiNmVmMmYwNmM5NTUwMDdkMDBjMzdkNzg5M2U0MzUzMTQyYzFhZTc1ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nCWRp-bZ-eAZINVC8ThBCEULfXKAQUU8fPtHnPK7iGc)

Its works. thanks sir
