### ISSUE TITLE
plz update

### ISSUE THREAD

**Issue by guraismy** [swordbluesword/PalWorld-NetCrack#15]

**Comment by Petelgeuse95** [comment]
> Doesn't matter if ya update... it's been patched.

Don't spread wrong information, the latest commit eith updated offset works on 1.3.0

**Comment by Chaos192** [comment]
> > Doesn't matter if ya update... it's been patched.
> 
> Don't spread wrong information, the latest commit eith updated offset works on 1.3.0

Pal spawning has been patched so it's not wrong info, only useful thing really is that.
