### ISSUE TITLE
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

### ISSUE THREAD

**Issue by darkmathew** [swordbluesword/PalWorld-NetCrack#2]
## Behaviour
I'm facing an issue with the stability of the cheat here. I can inject into the game process normally, but a few seconds after pressing the INSERT hotkey, the game closes, and the Unreal Engine 5 error screen appears.

## Injection
I'm using the GH Injector for this job.
![GHINJECTPALWORLD1](https://github.com/swordbluesword/PalWorld-NetCrack/assets/78329418/f12688ec-9bdf-48e0-af71-10230315a935)

## Unreal Crash
The error it displays indicates a problem in the following code snippet:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

NetCrack_PalWorld!DetourTick() [D:\Downloads\PalWorld-NetCrack-master\PalWorld-NetCrack-master\config.cpp:11]
Palworld_Win64_Shipping!UPalOptionSubsystem::FOnChangeKeyConfigDelegate_DelegateWrapper()

![PALWORLDERRORSCREEN](https://github.com/swordbluesword/PalWorld-NetCrack/assets/78329418/dc873e79-a941-41bf-b94d-9550bdcf6ddb)

**Comment by itzkaydo** [comment]
Make sure your on DX11, also try to use a different injector,  i use Process Hacker and have no issues, and ive added quiet alot to my fork aswell as a fully working ESP.

**Comment by darkmathew** [comment]
> Make sure your on DX11, also try to use a different injector, i use Process Hacker and have no issues, and ive added quiet alot to my fork aswell as a fully working ESP.

In fact... the injector doesn't matter in this case (note: I also use the Extreme Injector), the injection occurs normally. There is a problem with the DetourTick() function call. I'll check more later. Thanks for the help, anyway.

**Comment by darkmathew** [comment]
After 1.3.0 Update all works fine. Great Work Guys!
