### ISSUE TITLE
How to compile 

### ISSUE THREAD

**Issue by Armedorrr** [swordbluesword/PalWorld-NetCrack#22]
need help compiling into dll file

am noob

**Comment by Armedorrr** [comment]
getting error 

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'SDK.hpp': No such file or directory	NetCrack-PalWorld	C:\Users\Armedor\source\repos\PalWorld-NetCrack\include\Menu.hpp	3

**Comment by Armedorrr** [comment]
im also getting 
Error (active)	E0020	identifier "FSoftObjectPath" is undefined	NetCrack-PalWorld	C:\Users\Armedor\source\repos\PalWorld-NetCrack 1\SDK\Basic.hpp	458

**Comment by senseirain** [comment]
I want to know too xD

**Comment by Petelgeuse95** [comment]
> getting error
> 
> Severity Code Description Project File Line Suppression State Details Error C1083 Cannot open include file: 'SDK.hpp': No such file or directory NetCrack-PalWorld C:\Users\Armedor\source\repos\PalWorld-NetCrack\include\Menu.hpp 3

I don't know, but did you extract the zip out...?

**Comment by qh1327966381** [comment]
怎么运行 等待ing

**Comment by Petelgeuse95** [comment]
> 怎么运行 等待ing

编译好了 你可以用Extreme Injector (github 开源) 注入去palworld
热键是Insert

**Comment by khristopherw** [comment]
1. Extract the .zip into a folder.
2. Install VS Studio 2022 and install all C++ packages.
3. Then, open the project solution (DX11-Base.sln). 
4. At the top bar, you will probably see Either Debug x64 or Release x64. Make sure it's set to Release x64. 
5. On the right, you will see the solution explorer. Right click on NetCrack-Palword, and press Build (NOT Build Solution). Then wait for it to finish compiling. It'll tell you at the bottom.
Then, inside of the folder you extracted it into, you will see a folder called x64. The dll is inside of there.

**Comment by senseirain** [comment]
Dayum I was doing it wrong all this time was doing Batch Build xD

**Comment by RazielWasTaken** [comment]
i did it but only speedhack work anyone know how to fix?

**Comment by qh1327966381** [comment]
> 1. 将 .zip 解压缩到文件夹中。
> 2. 安装 VS Studio 2022 并安装所有 C++ 软件包。
> 3. 然后，打开项目解决方案 （DX11-Base.sln）。
> 4. 在顶部栏中，你可能会看到“调试 x64”或“版本 x64”。确保将其设置为“版本 x64”。
> 5. 在右侧，你将看到解决方案资源管理器。右键单击 NetCrack-Palword，然后按 Build（而不是 Build Solution）。然后等待它完成编译。它会在底部告诉你。然后，在将其解压缩到的文件夹中，您将看到一个名为 x64 的文件夹。dll在里面。

哥们感谢你

**Comment by qh1327966381** [comment]
请问：现在它这个是不能生成Pal了吗

**Comment by asd62033** [comment]
only Speed hack can use, no idea

**Comment by geocine** [comment]
I use exterme injector to inject the dll, now how can I use it?

**Comment by Kribirpc** [comment]
c1010 error, line 147 whats mean?

**Comment by JohnCale47** [comment]
```
'ImVec2::ImVec2': no overloaded function could convert all the argument types
1>	C:\Users\johnc\Downloads\PalWorld-NetCrack-master\libs\ImGui\imgui.h(271,1):
1>	could be 'ImVec2::ImVec2(ImVec2 &&)'
1>		C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,51):
1>		'ImVec2::ImVec2(ImVec2 &&)': cannot convert argument 1 from 'int' to 'ImVec2 &&'
1>			C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,94):
1>			Reason: cannot convert from 'int' to 'ImVec2'
1>	C:\Users\johnc\Downloads\PalWorld-NetCrack-master\libs\ImGui\imgui.h(271,1):
1>	or       'ImVec2::ImVec2(const ImVec2 &)'
1>		C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,51):
1>		'ImVec2::ImVec2(const ImVec2 &)': cannot convert argument 1 from 'int' to 'const ImVec2 &'
1>			C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,94):
1>			Reason: cannot convert from 'int' to 'const ImVec2'
1>	C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,51):
1>	while trying to match the argument list '(int)'
1>Done building project "DX11-Base.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 12:36 PM and took 07.022 seconds ==========
```

why is it failiing ?

**Comment by geocine** [comment]
> ```
> 'ImVec2::ImVec2': no overloaded function could convert all the argument types
> 1>	C:\Users\johnc\Downloads\PalWorld-NetCrack-master\libs\ImGui\imgui.h(271,1):
> 1>	could be 'ImVec2::ImVec2(ImVec2 &&)'
> 1>		C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,51):
> 1>		'ImVec2::ImVec2(ImVec2 &&)': cannot convert argument 1 from 'int' to 'ImVec2 &&'
> 1>			C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,94):
> 1>			Reason: cannot convert from 'int' to 'ImVec2'
> 1>	C:\Users\johnc\Downloads\PalWorld-NetCrack-master\libs\ImGui\imgui.h(271,1):
> 1>	or       'ImVec2::ImVec2(const ImVec2 &)'
> 1>		C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,51):
> 1>		'ImVec2::ImVec2(const ImVec2 &)': cannot convert argument 1 from 'int' to 'const ImVec2 &'
> 1>			C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,94):
> 1>			Reason: cannot convert from 'int' to 'const ImVec2'
> 1>	C:\Users\johnc\Downloads\PalWorld-NetCrack-master\src\Menu.cpp(395,51):
> 1>	while trying to match the argument list '(int)'
> 1>Done building project "DX11-Base.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> ========== Build completed at 12:36 PM and took 07.022 seconds ==========
> ```
> 
> why is it failiing ?

check my PR https://github.com/swordbluesword/PalWorld-NetCrack/pull/29
