### ISSUE TITLE
您好，我想知道如何获取的offset_Tick？

### ISSUE THREAD

**Issue by ScatteredSnow** [swordbluesword/PalWorld-NetCrack#3]
请问能否告知呢？

**Comment by itzkaydo** [comment]
> Could you please tell me?

offset_Tick = 0x2AB44D0

**Comment by ScatteredSnow** [comment]
> > 你能告诉我吗？
> 
> offset_Tick = 0x2AB44D0

这个数值是如何得到的呢，由于我玩的是学习版，这个数值好像不对，我想知道咋获取我去更新他

**Comment by swordbluesword** [comment]
Open your IDA, quickly filter "APalPlayerCharacter::tick" in the function list, and go to the function header to get its offset

**Comment by ScatteredSnow** [comment]
> Owner

Okay, thank you very much for your answer

**Comment by gir489returns** [comment]
> Might aswell use dumper-7 to dump xbox store version SDK and use that to make sure all offsets are right ?

I tried doing this, it throws 100 errors about redefinitions. I made them go away and got it to compile, but it still doesn't work, nothing from the menu works when I click it.
