### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by mrfurquim** [swordbluesword/PalWorld-NetCrack#34]
I compiled it successfully but I don't know what to do with the dll after that.

Would it be just getting a dll injector and injecting it?

Can anyone make a simple tutorial?

Another question, is it for online or offline server?

**Comment by elvrik** [comment]
Compile DLL. Start game , and use DLL Injector, Cheat Engine, Process Hacker or any you like. After complete intiliazing press in game INSERT to call the cheat menu.

**Comment by OfficialModdz** [comment]
Compiled it after adding the include and lib files to the project, INS doesn't work... the game did have an 18 gb update maybe the offsets have changed?

**Comment by elvrik** [comment]
> Compiled it after adding the include and lib files to the project, INS doesn't work... the game did have an 18 gb update maybe the offsets have changed?

Donts think so, i have actual update of the game and this DLL. Its still working perfectly on dedicated server
