### ISSUE TITLE
stop giving code to this "ShieldSupporter" from UC 

### ISSUE THREAD

**Issue by Gravity0night** [swordbluesword/PalWorld-NetCrack#38]
he begs for code everywhere even in discord ,after it he's bluffing with "Pictures" claim he did everything code everything on his own discord .
collect all the codes from others and never share since 2021 , i know this kids for years .
and I saw him did the same shit again , what a prick , guess what he would do if someone ask him to let others to see his "code" ? 
：OH SORRY ITS STILL WIP AND I DON'T WANT TO SHARE IT

**Comment by Petelgeuse95** [comment]
> he begs for code everywhere even in discord ,after it he's bluffing with "Pictures" claim he did everything code everything on his own discord . collect all the codes from others and never share since 2021 , i know this kids for years . and I saw him did the same shit again , what a prick , guess what he would do if someone ask him to let others to see his "code" ? ：OH SORRY ITS STILL WIP AND I DON'T WANT TO SHARE IT

So... what u want is make this repo private? i dont get u

**Comment by itzkaydo** [comment]
https://github.com/itzkaydo/SoTMaulder-PalWorld
LMFAO all of my shit is public u fucking autist, do you not know what a open source cheat is? plus i give credits to everything, so suck my weiner, faggot.
