### ISSUE TITLE
No Release?

### ISSUE THREAD

**Issue by Mangaia** [swordbluesword/PalWorld-NetCrack#4]
Hi, how can I compile it, or could you release it? Thanks!

**Comment by Sinnisterly** [comment]
can't have release via UC's forum rules. Compile it via visual studio, plenty of guides on how online.

**Comment by Mangaia** [comment]
Couldn't compile : 
![image](https://github.com/swordbluesword/PalWorld-NetCrack/assets/21020827/1851b84f-7dc9-4751-99c6-87c855f53985)
1>Generating Code...
1>C:\Users\HomePC\Downloads\PalWorld-NetCrack-master\SDK\Pal_functions.cpp : fatal  error C1128: number of sections exceeded object file format limit: compile with /bigobj
1>Done building project "DX11-Base.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 12:49 AM and took 20,399 seconds ==========

**Comment by itzkaydo** [comment]
> Couldn't compile : ![image](https://private-user-images.githubusercontent.com/21020827/299124400-1851b84f-7dc9-4751-99c6-87c855f53985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTA2MzAsIm5iZiI6MTcwNjA1MDMzMCwicGF0aCI6Ii8yMTAyMDgyNy8yOTkxMjQ0MDAtMTg1MWI4NGYtN2RjOS00NzUxLTk5YzYtODdjODU1ZjUzOTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIyNTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzdiYTExYjk5ZTIyNGMxM2M1OWQ5OGQ1YjQ0ZjRiNWEyOWQxMWYzMzA5ZjY4MDhlYjA3NDFmNmJlYWIwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C7O-L3rXRml001I0n4KDkxP_QjUuTxS4HjoFYhvXAng) 1>Generating Code... 1>C:\Users\HomePC\Downloads\PalWorld-NetCrack-master\SDK\Pal_functions.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj 1>Done building project "DX11-Base.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== ========== Build started at 12:49 AM and took 20,399 seconds ==========

dont be lazy, go to UC, dozens of posts on how to fix this

**Comment by Mangaia** [comment]
I'm not lazy, I just don't know how and what to do. That is the reason. Not a coder by any means, was just following semi-simple instructions on how to load and build.

**Comment by Mangaia** [comment]
> > Couldn't compile : ![image](https://private-user-images.githubusercontent.com/21020827/299124400-1851b84f-7dc9-4751-99c6-87c855f53985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTA2MzAsIm5iZiI6MTcwNjA1MDMzMCwicGF0aCI6Ii8yMTAyMDgyNy8yOTkxMjQ0MDAtMTg1MWI4NGYtN2RjOS00NzUxLTk5YzYtODdjODU1ZjUzOTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIyNTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzdiYTExYjk5ZTIyNGMxM2M1OWQ5OGQ1YjQ0ZjRiNWEyOWQxMWYzMzA5ZjY4MDhlYjA3NDFmNmJlYWIwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C7O-L3rXRml001I0n4KDkxP_QjUuTxS4HjoFYhvXAng) 1>Generating Code... 1>C:\Users\HomePC\Downloads\PalWorld-NetCrack-master\SDK\Pal_functions.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj 1>Done building project "DX11-Base.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== ========== Build started at 12:49 AM and took 20,399 seconds ==========
> 
> dont be lazy, go to UC, dozens of posts on how to fix this

I added /bigobj that should've fixed it, but it still doesn't compile.

**Comment by MGJerry** [comment]
@Mangaia if you still looking for answers then here
![image](https://github.com/swordbluesword/PalWorld-NetCrack/assets/85227828/0a7c39d8-2395-4ab3-9846-783eeb64c618)

**Comment by Mangaia** [comment]
> @Mangaia if you still looking for answers then here ![image](https://private-user-images.githubusercontent.com/85227828/299258014-0a7c39d8-2395-4ab3-9846-783eeb64c618.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODgwMTksIm5iZiI6MTcwNjA4NzcxOSwicGF0aCI6Ii84NTIyNzgyOC8yOTkyNTgwMTQtMGE3YzM5ZDgtMjM5NS00YWIzLTk4NDYtNzgzZWViNjRjNjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5MTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMGFjOTBiOWQyNmNmOTRhZGEzYTNlODRiY2U5MjM2NzI5ZWM3Mjk4NDlhNDRkZTk2MjYxZmU4MTQ5YTkzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IyYSwjB8CXQJZtgowcltaxes0x7NbaoyLMtAQvD0HV8)

Thank you! However, I already tried and everything is as this man states. And it still fails. 


`1>Generating Code...
1>C:\Users\HomePC\Downloads\PalWorld-NetCrack-master\SDK\Pal_functions.cpp : fatal  error C1128: number of sections exceeded object file format limit: compile with /bigobj
1>Done building project "DX11-Base.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 11:17 AM and took 17,624 seconds ==========`

**Comment by MGJerry** [comment]
Yeah, you literally right-click the project, go to properties and add "/bigobj" like I've done here
![image](https://github.com/swordbluesword/PalWorld-NetCrack/assets/85227828/2e712334-e375-4e9d-bce8-f5f872c06869)

It's that simple

**Comment by MGJerry** [comment]
You can try pulling from the repo and recompile (also change to buildtools v143 specifically to see if it's that)
![image](https://github.com/swordbluesword/PalWorld-NetCrack/assets/85227828/9782c0f1-946e-4b39-a2f5-a62534e022c5)

**Comment by MGJerry** [comment]
> Already checked and it is all as you say. I will try to pull it again from the repo, see if that works.

There's been quite some commits since you made the issue, somethings probably got changed around and stuff

**Comment by Mangaia** [comment]
> > Already checked and it is all as you say. I will try to pull it again from the repo, see if that works.
> 
> There's been quite some commits since you made the issue, somethings probably got changed around and stuff

Okay, well, not the same issue, but failed again: 

1>D:\GitHubRepos1\include\Menu.hpp(3,10): fatal  error C1083: Cannot open include file: 'SDK.hpp': No such file or directory
1>Generating Code...
1>Done building project "DX11-Base.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 11:38 AM and took 22,666 seconds ==========

**Comment by MGJerry** [comment]
> Okay, well, not the same issue, but failed again:
> 
> 1>D:\GitHubRepos1\include\Menu.hpp(3,10): fatal error C1083: Cannot open include file: 'SDK.hpp': No such file or directory 1>Generating Code... 1>Done building project "DX11-Base.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== ========== Build started at 11:38 AM and took 22,666 seconds ==========

You forgor the Additional Include Directories in C/C++ > General

**Comment by Mangaia** [comment]
> > Okay, well, not the same issue, but failed again:
> > 1>D:\GitHubRepos1\include\Menu.hpp(3,10): fatal error C1083: Cannot open include file: 'SDK.hpp': No such file or directory 1>Generating Code... 1>Done building project "DX11-Base.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== ========== Build started at 11:38 AM and took 22,666 seconds ==========
> 
> You forgor the Additional Include Directories in C/C++ > General

I have no idea how to do that, but I checked online so I tried /I SDK.hpp but that didn't work...

![image](https://github.com/swordbluesword/PalWorld-NetCrack/assets/21020827/7a502210-494f-45a0-93e3-1fa31cc8e06c)

**Comment by Mangaia** [comment]
> > Okay, well, not the same issue, but failed again:
> > 1>D:\GitHubRepos1\include\Menu.hpp(3,10): fatal error C1083: Cannot open include file: 'SDK.hpp': No such file or directory 1>Generating Code... 1>Done building project "DX11-Base.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== ========== Build started at 11:38 AM and took 22,666 seconds ==========
> 
> You forgor the Additional Include Directories in C/C++ > General

Okay, well I selected something and now it worked, finally T_T

**Comment by MGJerry** [comment]
> Okay, well I selected something and now it worked, finally T_T

Noice, now just inject it into the game process and you're done

**Comment by Mangaia** [comment]
> > Okay, well I selected something and now it worked, finally T_T
> 
> Noice, now just inject it into the game process and you're done

I just tried with Xenos, but it doesn't seem to work. Loads up this, but clicking "Insert" doesn't do anything.

**Comment by Mangaia** [comment]
> > Okay, well I selected something and now it worked, finally T_T
> 
> Noice, now just inject it into the game process and you're done

Nevermind. I had to inject it in the Palworld-Win64-shipping.exe ...
