### ISSUE TITLE
When i press the insert key nothing happens

### ISSUE THREAD

**Issue by Imzeroo** [swordbluesword/PalWorld-NetCrack#40]
i compiled it and injected it but when i press insert nothing happens pls sned help

**Comment by merlin7o** [comment]
try insert+fn

**Comment by merlin7o** [comment]
prt sc insert+fn

**Comment by Imzeroo** [comment]
nope didnt help :/

**Comment by Imzeroo** [comment]
i injected it into the wrong exe :(
