### ISSUE TITLE
XBOX version?

### ISSUE THREAD

**Issue by gir489returns** [swordbluesword/PalWorld-NetCrack#5]
I'm trying to update this for the XBOX version, and I'm having trouble finding all the offsets.

config.h had offset_Tick which is 0x29A4CE0 and SDK.hpp had GObjects, AppendString and ProcessEvent which are 0x080FB834, 0x02BE1BB0 and 0x02D647F0. It makes it harder to do the XBOX version because there is no PDB giving us the function names you mentioned in https://github.com/swordbluesword/PalWorld-NetCrack/issues/3#issuecomment-1906874983. I had to basically generate signatures and match up the function/offsets so I'm not entirely sure they're correct either.

What else needs to be updated? Because the cheat still does not work.

**Comment by gir489returns** [comment]
I got it working. Here's my current working branch.

https://github.com/gir489returns/PalWorld-NetCrack-XBOX

**Comment by swordbluesword** [comment]
nice

**Comment by BlueSAES** [comment]
could you help me out? does it still work if so could you give me a quick tuto about running it
