### ISSUE TITLE
Error	LNK1104	cannot open file 'PalworldSDKd.lib'

### ISSUE THREAD

**Issue by fordft168** [swordbluesword/PalWorld-NetCrack#62]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK1104	cannot open file 'PalworldSDKd.lib'	NetCrack-PalWorld	D:\PalWorld-NetCrack-master\LINK	1

**Comment by Wayzonline** [comment]
https://github.com/swordbluesword/PalWorld-NetCrack/issues/58#issuecomment-1916306465

Here we go :3

**Comment by fordft168** [comment]
tysm
