### ISSUE TITLE
number of sections exceeded object file format limit

### ISSUE THREAD

**Issue by K2NK** [swordbluesword/PalWorld-NetCrack#8]
got this messages while trtying to build

**Comment by xCENTx** [comment]
> Right click solution -> Properties
> C/C++: All Options -> Additional Options: "/bigobj" 
Alternatively you can compile in "Release Mode"
![image](https://github.com/swordbluesword/PalWorld-NetCrack/assets/80198020/6d4603f3-4782-4b01-ae6f-dca5f6c11d7e)

**Comment by K2NK** [comment]
Thank you!
